const SHOP_DATA =[
  {
    "id":1,
    "name": "Ajrakh block printed Saree",
    "description": "Classy and elegant in a lovely, soft Chanderi Saree with Ajrakh block printing and a Temple border.The saree comes with a co-ordinated blouse piece. Possibly the oldest known method of block printing in India dating back to the Indus Valley Civilisation, Ajrakh printing uses only wooden blocks and natural dyes and is a long and laborious process that entails the precise synchronising of the print on both sides of the fabric before dyeing it one colour at a time. In Arabic, Ajrakh means blue or indigo, Which is dominantly used in Ajrakh printing and hence the word. Patterned in intense jewel like colors, the dominant colors are rich crimson and a deep indigo and bits of white and black to give definition to the geometric patterns. Ajrakh colors emerge best on cotton fabric. These days silk is also used. As wood absorbs the color better and more uniformly, only wooden blocks are used in Ajrakh printing.",
    "category": "Women",
    "category_id":1,
    "sub_id":1,
    "sub_Cat": "saree",
    "price": 4480,
    "state": "Gujarat",
    "craft": "Ajrakh",
    "material": "Chanderi",
    "image": "https://i.postimg.cc/Bt9h9qG0/Ajrak.png"
  },
  {
    "id":2,
    "name": "Pure Handwoven Matka Silk Saree",
    "description": "Stunning in a blue classic ultra-soft Matka Silk Saree. Beautifully handwoven Matka silk sarees by artisans from Bengal, these elegant, soft sarees are a lovely style statement indeed! This lovely piece has an all over self motif woven into the saree for that understated yet dressy look.",
    "category": "Women",
    "category_id":1,
    "sub_id":1,
    "sub_Cat": "saree",
    "price": 8490,
    "state": "West Bengal",
    "craft": "Assorted cloth weaving",
    "material": "Matka silk",
    "image": "https://i.postimg.cc/xdsC8889/BlueSilk.png"
  },

  {
    "id":3,
    "name": "Sabai Grass Handmade Tote Bag",
    "description": " Opt for some boho-chic with this classic handcrafted Sabai grass tote bag! • Made with Sabai grass, this roomy utility side bag measures 15x1.5x12.5 inches with a strap length of 20 inches. • The Sabai Grass Tote Bag is handmade by skilled artisans who are masters of the craft form. The traditional craft of weaving home decoration items or furniture out of Sabai grass is popular among rural Bankura, Purulia and West Midnapore in West Bengal. Women of the lower-income families from this region use the durable natural fibre for weaving a variety of sophisticated handiworks for economic sustenance.",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":1520,
    "state": "West Bengal",
    "craft": "Sabai Grass weaving",
    "material": "Sabai Grass",
    "image": "https://i.postimg.cc/FHfjgttb/grassbag.png"
  },
  {
    "id":4,
    "name": "Jute & Fabric Tote / Sling Bag",
    "description": "A beautifully handcrafted eco-friendly and stylish accessory. This unique craft perfected by village artisans from Uttarakhand involves weaving Jute and recycled fabric into lovely designs to create a range of beautiful home and personal accessories.",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":1150,
    "state": "Uttarakhand",
    "craft": "Jute Craft",
    "material": "Jute & Cloth",
    "image": "https://i.postimg.cc/dt3dwM0M/jutes-bag.png"
  },
  {
    "id":5,
    "name": "Jawaja Leather Bag",
    "description": "A Jawaja Leather Craft Product - Leather Bag with Hand Stitch Detail. A smart, elegant accessory that makes for a unique style statement. Jawaja Leather Craft traditionally practiced by the Regar community of Rajasthan, dates back to over three centuries ago. This bag comes with a colourful flap with a magnetic button, front pocket, a front pocket with zipper, inner pocket with zipper and a long adjustable strap.",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":2100,
    "state": "Rajasthan",
    "craft": "Jawaja Leather Craft",
    "material": "Leather",
    "image": "https://i.postimg.cc/50mvNbvJ/Jawaja-Leather.png"
  },
  {
    "id":6,
    "name": "Blue Square Emb Pouch",
    "description": "Phulkari Hand crafted Embroidered Zip Pouch for all your small essentials. It makes a perfect wedding giveaway / favour. It is Embroidered with Phulkari motifs on front and back by machine first on a cotton blend fabric and the front is further embellished with Glass beads.This pouch has one main Zip compartment, YKK Plastic zipper and a hand made Tassel on the side.",
    "category": "Women",
    "category_id":1,
    "sub_id":3,
    "sub_Cat": "wallets",
    "price":500,
    "state": "Punjab",
    "craft": "Phulkari",
    "material": "Cotton",
    "image": "https://ibb.co/WG8ZtMX"
  },
  {
    "id": 7,
    "name": "Leather Clutch / Wallet",
    "description": "A Jawaja Leather Craft Product - Leather Clutch / Wallet with Hand Stitch Detail and Cutworkdesign. A smart and compact accessory, this multi-utility Clutch / Wallet opens out to offer you multiple compartments to safely hold all your essentials. Jawaja Leather Craft traditionally practiced by the Regar community of Rajasthan, dates back to over three centuries ago.",
    "category": "Women",
    "category_id":1,
    "sub_id":3,
    "sub_Cat": "wallets",
    "price":1400,
    "state": "Rajasthan",
    "craft": "Jawaja Leather Craft",
    "material": "Leather",
    "image": "https://i.postimg.cc/k48Cxgwr/Leather-wallet.png"
  },
  {
    "id":8,
    "name": "Ladakh Beadwork Clutch",
    "description": "Unique and lovely as a gift or personal accessory, this beautiful little bag with beautiful handcrafted beadwork from Ladakh will always draw attention with its vibrant appeal. Ladakh is undoubtedly India’s most remote region with an incomparable beauty. The tradition of artistic craftsmanship in Ladakh has come down through the centuries, originating mostly from the local tribes. ",
    "category": "Women",
    "category_id":1,
    "sub_id":3,
    "sub_Cat": "wallets",
    "price":1360,
    "state": "Ladakh",
    "craft": "Ladakh Beadwork",
    "material": "Cloth & Beads",
    "image": "https://i.postimg.cc/pL8mLPbS/Laddak-bead.png"
  },
  {
    "id":9,
    "name": "Jute & Fabric Sling Bag",
    "description": "A beautifully handcrafted eco-friendly and stylish accessory. This unique craft perfected by village artisans from Uttarakhand involves weaving Jute and recycled fabric into lovely designs to create a range of beautiful home and personal accessories.",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":1020,
    "state": "Uttarakhand",
    "craft": "Jute craft",
    "material": "Jute & Cloth",
    "image": "https://i.postimg.cc/SNHX4J58/jute-sling.png"
  },
  {
    "id":10,
    "name": "Zardozi Evening Bag",
    "description": "Silk evening bag with exquisite bead handles and the finest intricate Zardozi / mirrorwork embroidery - Cylindrical shape",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":2050,
    "state": "Uttar Pradesh",
    "craft": "Zardozi",
    "material": "Silk",
    "image": "https://i.postimg.cc/7hkkXrQ5/zardozi-bag.png"
  },
  {
    "id":11,
    "name": "Cotton Beads Neckpiece",
    "description": "Cool in Blue... lovely ocean colours and a perfect mood setter! A lovely multi- string neck piece crafted using cotton fabric beads.Made from different pieces of upcycled fabric by the very talented team at Padukas, a social enterprise committed to the upliftment of tribal women in the vicinity of their operation.Scraps of fabric are wrapped around and sewn into balls.",
    "category": "Women",
    "category_id":1,
    "sub_id":4,
    "sub_Cat": "jewellery",
    "price":2010,
    "state": "Maharashtra",
    "craft": "Bead Craft",
    "material": "Cotton Fabric Beads",
    "image": "https://i.postimg.cc/DwgKgNqZ/blue-neckpiece.png"
  },
  {
    "id":12,
    "name": "Silver Necklace",
    "description": "Silver Finish Traditional Necklace Heavy. The jewelry featured here is silver finish jewelry made from metal alloys in traditional designs, generally used for pure silver jewelry. Since the early 1900’s, beautiful silver jewelry has been handcrafted by craftsmen from Maharashtra as well as Rajasthan, who have been skilled in giving shape to ornate silver jewellery for over a century. ",
    "category": "Women",
    "category_id":1,
    "sub_id":4,
    "sub_Cat": "jewellery",
    "price":990,
    "state": "Maharashtra",
    "craft": "Other Metals",
    "material": "Metal Alloy",
    "image": "https://i.postimg.cc/d1Q36dkM/silver-Necklace.png"
  },
  {
    "id":13,
    "name": "Kashmiri Papier Mache Clutch",
    "description": "Exclusive, Fine art Papier-Mache Clutch Bag (with sling) - Deep Blue & Pink , featuring beautifully painted flowers from an exquisitely hand painted range - 'The Shahi Collection'! An ultimate example of the unmatched talent and skill of Kashmiri artisans. This exquisite Papier-Mache clutch bag with its old world elegance and charm leaves one mesmerised by the fine, intricate painting that adorns the clutch.",
    "category": "Women",
    "category_id":1,
    "sub_id":2,
    "sub_Cat": "bags",
    "price":2500,
    "state": "Kashmir",
    "craft": "Kashmiri Art",
    "material": "Paper Mache",
    "image": "https://i.postimg.cc/Hx3c13Ds/Kashmir-Bag.png"
  },
  {
    "id":14,
    "name": "Kantha Embroidered Silk Cushion cover",
    "description": "Embellished with beautiful and intricate Flower Kantha embroidery from West Bengal, this is a lovely handcrafted set, painstakingly made by rural artisans from the interiors of West Bengal.",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id":5,
    "sub_Cat": "cushioncovers",
    "price":1120,
    "state": "West Bengal",
    "craft": "Kantha Embroidery",
    "material": "Silk",
    "image": "https://i.postimg.cc/rwck5TR3/Cushion-Cover-blue.pngy"
  },
  {
    "id":15,
    "name": "Kantha Cushion Cover set",
    "description": "Embellished with beautiful and intricate Floral Kantha embroidery from West Bengal, this is a beautifully handcrafted elegant set to add that extra touch of class to your décor, painstakingly made by rural artisans from the interiors of West Bengal.",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id":5,
    "sub_Cat": "cushioncovers",
    "price":1940,
    "state": "West Bengal",
    "craft": "Kantha Embroidery",
    "material": "Cotton",
    "image": "https://i.postimg.cc/fWtDNBh2/Cushio-Cover-Floral.png"
  },
  {
    "id":16,
    "name": "Leather Craft Floor Lamp",
    "description": "Andhra Leather Craft - Floor Lamp Shade (Large) - Radha & Krishna (Blue). (Electrical fittings not included). The craft technique behind this beautiful translucent leather painted lamp shade from Andhra Pradesh is an offshoot of the traditional and popular shadow-puppet theatre tradition - 'Tholu Bommalata' - literally meaning 'the dance of leather dolls.' A vibrant and unique work of art to liven up a wall or corner!",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id": 6,
    "sub_Cat": "lamps",
    "price":5780,
    "state": "Andhra Pradesh",
    "craft": "Andhra Leather Craft",
    "material": "Leather",
    "image": "https://i.postimg.cc/c4vKPQD0/Lamp-Shade-floral.png"
  },
  {
    "id":17,
    "name": "Leather Craft floral Lamp",
    "description": "A beautiful 'Thomu Bommalata' Andhra Leather Lamp Shade. (Electrical fittings not included) This translucent leather painting art form from Andhra Pradesh was traditionally used to make puppets for the popular shadow-puppet theatre tradition of Andhra Pradesh -‘Tholu Bommalata’- literally meaning “the dance of leather dolls’. An ancient practice, wandering entertainers have for centuries disseminated the knowledge of Hindu epics and local folk tales to the remotest corners of the region, through this art form and tradition.",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id":6,
    "sub_Cat": "lamps",
    "price":1640,
    "state": "Andhra Pradesh",
    "craft": "Andhra Leather Craft",
    "material": "Leather",
    "image": "https://i.postimg.cc/QNz1bp1G/Lamp-Andhra.png"
  },

  {
    "id": 18,
    "name": "Channapatna Wooden Toy Rattle",
    "description": "Kit Kat Rattle is a unique wooden rattle. It's rotating arms fascinates children and adults alike. This toy is made using traditional lacware toy making techniques and is coloured with natural dyes.",
    "category": "Kids",
    "category_id":5,
    "price":500,
    "state": "Karnataka",
    "craft": "Channapatna Wood Craft",
    "material": "Wood",
    "image": "https://i.postimg.cc/pTjLCHRj/Wooden-Rattle.png"
  },
  {
    "id":19,
    "name": "Wooden 5-in-1 Doll Set",
    "description": "Handcrafted Wooden 5-in-1 Doll Set. This unique, rustic set of 5 dolls fit one inside the other and can be a source of great amusement for a young child. Wooden toy-making is a traditional craft of Uttar Pradesh, India. Bright and colourful lacquered toys are made by clusters of skilled craftsmen. According to the craftsmen, their ancestors specialized in ivory carving that enjoyed good patronage during the reign of the Mughal emperors and the British. ",
    "category": "Kids",
    "category_id":5,
    "price":540,
    "state": "Uttar Pradesh",
    "craft": "Wooden Toy Craft",
    "material": "Wood",
    "image": "https://i.postimg.cc/HkZTmKjN/Wooden-dollset.png"
  },
  {
    "id":20,
    "name": "Shirt Ikat Woven Fabric",
    "description": "Cool, casual and totally comfortable in a striking Ikat woven shirt in mercerised cotton. Perfect for summer days or casual evenings.",
    "category": "Men",
    "category_id":2,
    "price":1700,
    "state": "Orissa",
    "craft": "Ikat Print",
    "material": "Mercerised Cotton",
    "image": "https://i.postimg.cc/XYyCBwFQ/Ikat-Men.png"
  },
  {
    "id":21,
    "name": "Raw Silk Embroidery wall Art",
    "description": "Raw Silk with Fine Kutch Embroidery - Small Wall Hanging. This exquisitely embroidered wall hanging has been handcrafted by women of the Kutch region in Gujarat. This region has been renowned for its mirrored embroidery either on Mushroo silk or cotton.",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id":7,
    "sub_Cat": "wallart",
    "price":1500,
    "state": "Gujarat",
    "craft": "Kutch Embroidery & Patchwork",
    "material": "Raw silk",
    "image": "https://i.postimg.cc/C16h42pD/wallart-1.png"
  },
  {
     "id":22,
    "name": "Burdwan Wooden Bride & Groom",
    "description": "A beautiful Burdwan Wooden Curio – Bride & Groom (Set of 2). Handcrafted by artisans from Bengal, this unique artefact is a vibrant, attractive decor item, perfect to brighten up a special corner as a table curio or a wall piece. ",
    "category": "HomeLiving",
    "category_id":3,
    "sub_id":7,
    "sub_Cat": "wallart",
    "price":1350,
    "state": "West Bengal",
    "craft": "Burdwan Wood craft",
    "material": "wood",
    "image": "https://i.postimg.cc/pVzVjq19/wallart-2.png"
  },
  {
    "id":23,
    "name": "Embossed Leather Diary and Metallic",
    "description": "Add a little yellow warmth to your mundane routine with this handmade leather diary! This work accessory is the perfect gift for your creative colleagues.",
    "category": "Gifts",
    "category_id":6,
    "sub_id":8,
    "sub_Cat": "diaries",
    "price":950,
    "state": "Rajasthan",
    "craft": "Leather craft",
    "material": "Leather /handmade paper",
    "image": "https://i.postimg.cc/WzJ9HdC8/gift-1.png"
  },
  {
   "id":24,
    "name": "Handcrafted Sabai Grass Coasters",
    "description": "A beautifully crafted set of Sabai grass table coasters (Dull Purple & Beige, set of 6), by rural artisans from the interiors of Bengal and Orissa.",
    "category": "Gifts",
    "category_id":6,
    "sub_id":9,
    "sub_Cat": "coasters",
    "price":700,
    "state": "West Bengal",
    "craft": "Grass weaving",
    "material": "Sabai Grass",
    "image": "https://i.postimg.cc/FFMms3r9/gift-2.png"
  },
  {
    "id":25,
    "name": "Warli Art Wooden Coaster Set",
    "description": "A beautiful, handcrafted set of Warli art coasters hand painted by tribal artisans that will always be appreciated for its unique appeal (Green Folk Art, Set of 6).",
    "category": "Gifts",
    "category_id":6,
    "sub_id":9,
    "sub_Cat": "coasters",
    "price":1000,
    "state": "Maharashtra",
    "craft": "Warli art",
    "material": "Wood",
    "image": "https://i.postimg.cc/5tCSJhn9/gift-3.png"
  }
]

export default SHOP_DATA;